/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20 } from "./Erc20";
export type { Erc20_bytes32 } from "./Erc20_bytes32";
export * as factories from "./factories";
export { Erc20_bytes32__factory } from "./factories/Erc20_bytes32__factory";
export { Erc20__factory } from "./factories/Erc20__factory";
